export enum UserEnums {
  SUCCESS = 'SUCCESS',
  ALREADY_LOGGED_OUT = 'ALREADY_LOGGED_OUT',
  USER_NOT_FOUND = 'USER_NOT_FOUND'
}

export enum UserRoles {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ORGANIZATION_ADMIN = 'ORGANIZATION_ADMIN',
  ORGANIZATION_USER = 'ORGANIZATION_USER'
}
