version: '3.8'
name: elciess_containers

services:
  mongodb:
    image: mongo:6.0
    container_name: localMongoDb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: elciess
      MONGO_INITDB_ROOT_PASSWORD: elciessPass
    volumes:
      - ./data:/data/db
    networks:
      - meu-local-network

networks:
  meu-local-network:
    driver: bridge
